version: '3.9'

services:
  mssql_db:
    container_name: mssql
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: Developer
      SA_PASSWORD: "qwerty123456"
    volumes:
      - mssqlsystem:/var/opt/mssql
      - mssqluser:/var/opt/sqlserver
    ports:
      - "1433:1433"
    restart: unless-stopped

volumes:
  mssqlsystem:
  mssqluser: